name: Deploy

on:
  workflow_call:
    inputs:
      deploy_environment:
        required: true
        type: string
      version:
        required: true
        type: string
      app:
        required: false
        type: string
        default: reg-check-api
      ecr_repo:
        required: false
        type: string
        default: register-checker-api-repo

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set secret name prefix
        id: set-deployment-env
        run: |
          DEPLOY_ENV=${{ inputs.deploy_environment }}

          if [ $DEPLOY_ENV != "test" ]
          then
            echo "SECRET_PREFIX=${DEPLOY_ENV^^}_" >> $GITHUB_ENV
          fi
          if [ $DEPLOY_ENV != "test2" ]
          then
            echo "tf_env_name=${DEPLOY_ENV}" >> $GITHUB_OUTPUT
          else
            echo "tf_env_name=tst2" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets[format('{0}AWS_ACCESS_KEY_ID', env.SECRET_PREFIX)] }}
          aws-secret-access-key: ${{ secrets[format('{0}AWS_SECRET_ACCESS_KEY', env.SECRET_PREFIX)] }}
          aws-region: eu-west-2

      # Note that the base Task Definition is managed by Terraform
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition "${{steps.set-deployment-env.outputs.tf_env_name}}-${{inputs.app}}-ecs-task-definition" \
          --query taskDefinition > task-definition.json

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{steps.set-deployment-env.outputs.tf_env_name}}-${{inputs.app}}-ecs-container
          image: ${{ steps.login-ecr.outputs.registry }}/${{inputs.ecr_repo}}:${{ inputs.version }}

      - name: Update appspec file for environment
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{env}"
          replace: ${{steps.set-deployment-env.outputs.tf_env_name}}
          include: "**/appspec.yaml"
          regex: false

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{steps.set-deployment-env.outputs.tf_env_name}}-${{inputs.app}}-ecs-service
          cluster: ${{steps.set-deployment-env.outputs.tf_env_name}}-${{inputs.app}}-ecs-cluster
          wait-for-service-stability: true
          codedeploy-appspec: ${{ github.workspace }}/.github/workflows/files/appspec.yaml
          codedeploy-application: ${{steps.set-deployment-env.outputs.tf_env_name}}-${{inputs.app}}
          codedeploy-deployment-group: ${{steps.set-deployment-env.outputs.tf_env_name}}-${{inputs.app}}-deployment-group
