name: "Hotfix: Tag and deploy to Test"

on:
  push:
    branches:
      - hotfix/v*

jobs:
  check-untagged:
    runs-on: ubuntu-latest
    outputs:
      untagged: ${{ !startsWith(env.MATCHING_TAGS, 'v') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check untagged (don't run for branch creation)
        id: get-matching-tags
        shell: bash
        run: |
          MATCHING_TAGS=$(git tag --contains HEAD)
          echo "Matching tags: $MATCHING_TAGS"
          echo "MATCHING_TAGS=$MATCHING_TAGS" >> $GITHUB_ENV
          
  build-and-tag:
    runs-on: ubuntu-latest
    needs: check-untagged
    if: needs.check-untagged.outputs.untagged == 'true'
    outputs:
      version: ${{ steps.get-latest-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Get minor version of branch
        shell: bash
        run: |
          echo "${{ needs.check-untagged.outputs.untagged }}"
          BRANCH_VERSION=${GITHUB_REF#refs/*/hotfix/}
          BRANCH_VERSION=${BRANCH_VERSION%.*}
          echo "BRANCH_VERSION=$BRANCH_VERSION" >> $GITHUB_ENV

      - name: Get latest patch version tag for minor version
        id: get-latest-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: cabinetoffice/eip-ero-register-checker-api
          releases-only: false
          prefix: '${{ env.BRANCH_VERSION }}'

      - name: Bump patch version tag
        uses: cabinetoffice/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch

      - name: Push version tag
        run: |
          tag=${{ steps.bump-semver.outputs.new_version }}
          message='${{ github.event.head_commit.message }}'
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: print-api-repo
          IMAGE_TAG: ${{ steps.bump-semver.outputs.new_version }}
        run: |
          ./gradlew bootBuildImage
          IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag eip-ero-print-api:latest $IMAGE
          docker push $IMAGE
          echo "::set-output name=image::$IMAGE"

      - name: Configure AWS credentials (live env)
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR (live env)
        id: login-ecr-live
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR (live env)
        id: build-image-live
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-live.outputs.registry }}
          ECR_REPOSITORY: print-api-repo
          IMAGE_TAG: ${{ steps.bump-semver.outputs.new_version }}
        run: |
          IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag eip-ero-print-api:latest $IMAGE
          docker push $IMAGE
          echo "::set-output name=image::$IMAGE"

  deploy:
    needs: build-and-tag
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_environment: test
      version: ${{ needs.build-and-tag.outputs.version }}
    secrets: inherit
